language: python
cache:
  directories:
    - "$HOME/.cache/pip"
    - "$HOME/.nvm"
    - node_modules
    - wger/node_modules
sudo: false
python:
  - "3.6"

# Install the application
install:
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.31.4/install.sh | METHOD=script
    bash
  - ". $HOME/.nvm/nvm.sh"
  - nvm install $TRAVIS_NODE_VERSION
  - nvm use $TRAVIS_NODE_VERSION

  # Install requirements
  - pip install -r requirements.txt
  - npm install
  - pip install coveralls


services:
  - postgresql
addons:
  postgresql: "9.4"

# Create test databases
before_script:
  - psql -c 'create database test_wger;' -U postgres
  - invoke create-settings --settings-path ./wger/settings.py --database-type postgresql
  - invoke bootstrap-wger --settings-path ./wger/settings.py --no-start-server
  - invoke bootstrap-wger --settings-path ./wger/settings.py --no-start-server

# Do the tests
script:
  # Regular application
  - coverage run --source=wger manage.py test 

  # Code coverage
  - coverage report
  - coveralls

after_success:
  - coveralls
