# Generated by Django 2.2 on 2019-06-03 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymconfig',
            name='default_gym',
            field=models.ForeignKey(
                blank=True,
                help_text='Select the default gym for this installation. \
                This will assign all new registered users to this gym \
                and update all existing users without a gym.',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='gym.Gym', verbose_name='Default gym'),
        ),
    ]
