# Generated by Django 2.2 on 2019-06-20 17:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exercises', '0006_merge_20190611_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='description',
            field=models.TextField(default='Keeps the body fit', max_length=2000, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Description'),
        ),
    ]
