# Generated by Django 2.2 on 2019-06-20 04:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0006_merge_20190611_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='description',
            field=models.TextField(default='Keeps the body fit', max_length=2000, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Description'),
        ),
    ]
