# Generated by Django 2.2 on 2019-06-05 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0002_auto_20190603_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='license_author',
            field=models.CharField(blank=True, help_text='If you are not the author, enter the name or source here. This is needed for some licenses e.g. the CC-BY-SA.', max_length=50, null=True, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='nutritionplan',
            name='description',
            field=models.TextField(blank=True, help_text='A description of the goal of the plan, e.g. "Gain mass" or "Prepare for summer"', max_length=2000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='nutritionplan',
            name='has_goal_calories',
            field=models.BooleanField(default=False, help_text='Tick the box if you want to mark this plan as having a goal amount of calories. You can use the calculator or enter the value yourself.', verbose_name='Use daily calories'),
        ),
    ]
