# Generated by Django 2.2 on 2019-06-10 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0003_auto_20190606_1818'),
        ('nutrition', '0003_auto_20190605_2316'),
    ]

    operations = [
    ]
