# Generated by Django 2.2 on 2019-06-20 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0006_merge_20190611_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Language', verbose_name='Language'),
        ),
    ]
