# Generated by Django 2.2 on 2019-06-10 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0003_auto_20190610_1040'),
        ('gym', '0004_merge_20190610_1039'),
    ]

    operations = [
    ]
