# Generated by Django 2.2 on 2019-06-11 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0003_auto_20190605_1211'),
        ('gym', '0005_merge_20190610_1220'),
    ]

    operations = [
    ]
