# Generated by Django 2.2 on 2019-06-05 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190603_2136'),
        ('core', '0002_auto_20190603_1934'),
    ]

    operations = [
    ]
