# Generated by Django 2.2 on 2019-06-19 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_merge_20190611_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutlog',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.WorkoutSession'),
        ),
    ]
